apiVersion: v1
baseDomain: $baseDomain
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    azure:
      type: $controlMachineSize
      osDisk:
        diskSizeGB: 512
      zones: 
      - "1"
      - "2"
      - "3"
  replicas: $numControlReplicas
compute:
- hyperthreading: Enabled
  name: worker
  platform:
    azure:
      type: $workerMachineSize
      osDisk:
        diskSizeGB: 512 
      zones: 
      - "1"
      - "2"
      - "3"
  replicas: $numWorkerReplicas
metadata:
  name: $clusterName
networking:
  clusterNetwork:
  - cidr: 20.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 20.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  azure:
    baseDomainResourceGroupName: $baseDomainResourceGroup
    virtualNetwork: $vnetName
    networkResourceGroupName: $resourceGroupName
    controlPlaneSubnet: $subnetControlNodeName
    computeSubnet: $subnetWorkerNodeName
    cloudName: AzurePublicCloud
    outboundType: Loadbalancer
    region: $deployRegion
publish: External
pullSecret: '\{"auths":\{"cloud.openshift.com":\{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfYTQ1ZGY0ZWI5YzJjNDZiZTlmYWNmMmNiZjM1MWM3YTY6VDAwTkFaT1lONVlPTURTVzVUM1JCM0U4R0NQU0lZVERLU0M5TEhTSEZHUlRYUFhSWFZHS0xQQzU3MzdQNzZTRA==","email":"mch@sbf.dk"\},"quay.io":\{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfYTQ1ZGY0ZWI5YzJjNDZiZTlmYWNmMmNiZjM1MWM3YTY6VDAwTkFaT1lONVlPTURTVzVUM1JCM0U4R0NQU0lZVERLU0M5TEhTSEZHUlRYUFhSWFZHS0xQQzU3MzdQNzZTRA==","email":"mch@sbf.dk"\},"registry.connect.redhat.com":\{"auth":"fHVoYy1wb29sLWUzNjI4NTQ4LWNjYjQtNDRiMS05NmJkLTVhMWU3MWE1N2VhNjpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTBOR0ppT0RFeVl6RmtZemswTW1VMU9ERmxObUZpWVRCaFpXWTFNV1U0TkNKOS5LYkFQSmdVUlJrVGF0XzZiaTIxSkRsX2xlTTVFaWVSS2JMUWh3Y0JzWnpHd2FWVGJkUFlYVDVxYjJtNFB1MDdKQldEN3VyWU5sODFlaVM2N1BFSTk4VHA2MGs4Uzhld2Jnak1FRnVYaVZvR2w3d1NaakdIazVjVUxaQmxBM1c4N1ZYY2tBYmtzdWFVLTNsbXlFcjlVeDMweGNvZVRVdDFCbWFlOURJMHpYeExzZlFxWFNSWVNMaXlIMUR3TnkzRWRzRzBjWWM5amZKRzZyR0VpU2dreVZ6ZmVodGUtT2FRSHhObG1uZFc2Mjd2bl9uUUxQWS1Db3dxVmxrc1Fpc3B0cEFUMmpCcF8tZXY4aWUzMnh0dGE2Q25UUEc5Tjk1MVY1b3NfcWRwRkRfTUk1b3p1eVNmMjN3TTgtaEU0LXMtd21hWGl1VVBOUFVNTWY3ZTBnYUVmRk5sb3NyN01fZ2ltbjB4RFgtQnpfeWd5S0ROR1RXaHBOaE13NUtFQUpzUVp2Z2U1M1hhMkFDOF9Rd1A2NUFnRkNJdkxIZTFHSXN6cXA5T1lzUDdzY2p1SWVhV1UwZ3ZzOWVnS3VCVHhYN1RrNThidTJYOTJsV0I1VmEzRjJjbEtxNzdlNEF4YzNVQ1JqODJES0Nmb1puX3hqdms3MnNXV0x1aWZXUVlNQTFrY3VJdEROUXlrV2tRVk5xNHZSY2hhWXBNdWUtWUpzcE92clctM0s2a3RFNEJkdWwzV01Na21oeUJxeVo3bGxlbl9vQ3VxNEJyNXN0R2xXdEFMWGVXSHVrSjJvTVJlVXdNT3ZuanA2cGRiZWtTX1QxeHVmUEhBRmk4MVVaZDdZYTNFZmx0STJxVHVZVGxFM2MxOUhFNDl4MjFFZjNOOGZZVW9ENTkwYzBYdlBGNA==","email":"mch@sbf.dk"\},"registry.redhat.io":\{"auth":"fHVoYy1wb29sLWUzNjI4NTQ4LWNjYjQtNDRiMS05NmJkLTVhMWU3MWE1N2VhNjpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTBOR0ppT0RFeVl6RmtZemswTW1VMU9ERmxObUZpWVRCaFpXWTFNV1U0TkNKOS5LYkFQSmdVUlJrVGF0XzZiaTIxSkRsX2xlTTVFaWVSS2JMUWh3Y0JzWnpHd2FWVGJkUFlYVDVxYjJtNFB1MDdKQldEN3VyWU5sODFlaVM2N1BFSTk4VHA2MGs4Uzhld2Jnak1FRnVYaVZvR2w3d1NaakdIazVjVUxaQmxBM1c4N1ZYY2tBYmtzdWFVLTNsbXlFcjlVeDMweGNvZVRVdDFCbWFlOURJMHpYeExzZlFxWFNSWVNMaXlIMUR3TnkzRWRzRzBjWWM5amZKRzZyR0VpU2dreVZ6ZmVodGUtT2FRSHhObG1uZFc2Mjd2bl9uUUxQWS1Db3dxVmxrc1Fpc3B0cEFUMmpCcF8tZXY4aWUzMnh0dGE2Q25UUEc5Tjk1MVY1b3NfcWRwRkRfTUk1b3p1eVNmMjN3TTgtaEU0LXMtd21hWGl1VVBOUFVNTWY3ZTBnYUVmRk5sb3NyN01fZ2ltbjB4RFgtQnpfeWd5S0ROR1RXaHBOaE13NUtFQUpzUVp2Z2U1M1hhMkFDOF9Rd1A2NUFnRkNJdkxIZTFHSXN6cXA5T1lzUDdzY2p1SWVhV1UwZ3ZzOWVnS3VCVHhYN1RrNThidTJYOTJsV0I1VmEzRjJjbEtxNzdlNEF4YzNVQ1JqODJES0Nmb1puX3hqdms3MnNXV0x1aWZXUVlNQTFrY3VJdEROUXlrV2tRVk5xNHZSY2hhWXBNdWUtWUpzcE92clctM0s2a3RFNEJkdWwzV01Na21oeUJxeVo3bGxlbl9vQ3VxNEJyNXN0R2xXdEFMWGVXSHVrSjJvTVJlVXdNT3ZuanA2cGRiZWtTX1QxeHVmUEhBRmk4MVVaZDdZYTNFZmx0STJxVHVZVGxFM2MxOUhFNDl4MjFFZjNOOGZZVW9ENTkwYzBYdlBGNA==","email":"mch@sbf.dk"\}\}\}'
sshKey: '$sshPubKey'
